version: '3.9'
services:
  postgres:
    image: postgres:16.2-alpine
    restart: unless-stopped
    container_name: categoryTest
    ports:
      - 5432:5432
    environment:
      DEBUG: "false"
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB:  cat
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command:
      - "-c"
      - "log_statement=all"
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8384:8080
    environment:
      - 'TZ=Europe/Moscow'
