version: '3.8'

services:
  app:
    container_name: nestjs-app
    image: nestjs-test
    build: ..
    ports:
      - '3333:3333'
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
    env_file:
      - ./dev.env

  postgres:
    container_name: postgres-db
    image: postgres:16.2-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cat
    volumes:
      - ../postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
